function attendanceStatusBadge(status) { return `<span class="badge attendance-badge status-${status.toLowerCase()}">${escapeHtml(status)}</span>`; }
function loadAttendanceOptions() { const w = loadWorkspace(), opts = w.employees.map(e => `<option value="${e.id}">${escapeHtml(getEmployeeName(w, e.id))}</option>`).join(""); $("#attendanceEmployee").html(opts); $("#attendanceEmployeeFilter").html(`<option value="">All employees</option>${opts}`); if (!$("#attendanceDate").val()) $("#attendanceDate").val(getTodayDate()); }
function preventDuplicateAttendance(employeeId, date) { const id = $("#attendanceId").val(); return loadWorkspace().attendance.some(a => a.employeeId === employeeId && a.date === date && a.id !== id); }
function renderAttendanceStats() { const s = calculateAttendanceStats(loadWorkspace(), getTodayDate()), cards = [["Total Today", s.total, "Records"], ["Present", s.present, "On site"], ["Remote", s.remote, "Working remotely"], ["Absent", s.absent, "Missing today"]]; $("#attendanceStats").html(cards.map(([l, v, m]) => `<article class="summary-card"><p class="summary-label">${l}</p><p class="summary-value">${v}</p><p class="summary-meta">${m}</p></article>`).join("")); }
function getFilteredAttendance() { const w = loadWorkspace(), q = $("#attendanceSearch").val().toLowerCase(), date = $("#attendanceDateFilter").val(), employee = $("#attendanceEmployeeFilter").val(), status = $("#attendanceStatusFilter").val(); return w.attendance.filter(a => { const hay = [getEmployeeName(w, a.employeeId), a.notes, a.status, a.date].join(" ").toLowerCase(); return (!q || hay.includes(q)) && (!date || a.date === date) && (!employee || a.employeeId === employee) && (!status || a.status === status); }).sort((a, b) => b.date.localeCompare(a.date)); }
function renderAttendance() { const w = loadWorkspace(), rows = getFilteredAttendance(); $("#attendanceTableWrap").html(rows.length ? `<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Date</th><th>Employee</th><th>Status</th><th>Check In</th><th>Check Out</th><th>Notes</th><th class="text-end">Actions</th></tr></thead><tbody>${rows.map(a => `<tr><td class="mono">${formatDate(a.date)}</td><td>${escapeHtml(getEmployeeName(w, a.employeeId))}</td><td>${attendanceStatusBadge(a.status)}</td><td>${escapeHtml(a.checkIn || "-")}</td><td>${escapeHtml(a.checkOut || "-")}</td><td>${escapeHtml(a.notes)}</td><td class="text-end"><button class="btn btn-sm btn-outline-info" onclick="editAttendance('${a.id}')">Edit</button> <button class="btn btn-sm btn-outline-danger" onclick="deleteAttendance('${a.id}')">Delete</button></td></tr>`).join("")}</tbody></table></div>` : renderEmptyState("No attendance records match the filters.")); }
function markAttendance(event) { event.preventDefault(); const employeeId = $("#attendanceEmployee").val(), date = $("#attendanceDate").val(); if (preventDuplicateAttendance(employeeId, date)) return showStatus("Duplicate attendance prevented for this employee and date.", "danger"); const w = loadWorkspace(), id = $("#attendanceId").val(), now = new Date().toISOString(); const p = { id: id || generateId("att"), employeeId, date, status: $("#attendanceStatus").val(), checkIn: $("#checkIn").val(), checkOut: "", notes: $("#attendanceNotes").val().trim(), createdAt: now }; if (id) { w.attendance = w.attendance.map(a => a.id === id ? { ...a, ...p } : a); addActivityLog("Attendance", "Updated attendance", `Updated attendance for ${getEmployeeName(w, employeeId)}`); } else { w.attendance.unshift(p); addActivityLog("Attendance", "Marked attendance", `Marked ${getEmployeeName(w, employeeId)} as ${p.status}`); } saveWorkspace(w); showStatus("Attendance saved."); resetAttendanceForm(); renderAttendanceStats(); renderAttendance(); }
function editAttendance(id) { const a = loadWorkspace().attendance.find(item => item.id === id); if (!a) return; $("#attendanceFormTitle").text("Edit Attendance"); $("#attendanceId").val(a.id); $("#attendanceEmployee").val(a.employeeId); $("#attendanceDate").val(a.date); $("#attendanceStatus").val(a.status); $("#checkIn").val(a.checkIn); $("#attendanceNotes").val(a.notes); scrollTo({ top: 0, behavior: "smooth" }); }
function deleteAttendance(id) { const w = loadWorkspace(), a = w.attendance.find(item => item.id === id); if (!a || !confirm("Delete attendance record?")) return; w.attendance = w.attendance.filter(item => item.id !== id); saveWorkspace(w); addActivityLog("Attendance", "Deleted attendance", `Deleted attendance for ${getEmployeeName(w, a.employeeId)}`); showStatus("Attendance deleted.", "warning"); renderAttendanceStats(); renderAttendance(); }
function filterAttendance() { renderAttendance(); }
function resetAttendanceForm() { $("#attendanceFormTitle").text("Mark Attendance"); $("#attendanceForm")[0].reset(); $("#attendanceId").val(""); $("#attendanceDate").val(getTodayDate()); }
$(document).ready(function () { initShell("attendance"); loadAttendanceOptions(); renderAttendanceStats(); renderAttendance(); $("#attendanceForm").on("submit", markAttendance); $("#resetAttendanceForm").on("click", resetAttendanceForm); $("#attendanceSearch,#attendanceDateFilter,#attendanceEmployeeFilter,#attendanceStatusFilter").on("input change", filterAttendance); $("#clearAttendanceFilters").on("click", function () { $("#attendanceSearch,#attendanceDateFilter,#attendanceEmployeeFilter,#attendanceStatusFilter").val(""); renderAttendance(); }); });
