function loadDepartmentManagerOptions() { const w = loadWorkspace(); $("#managerId").html(`<option value="">No manager</option>${w.employees.map(e => `<option value="${e.id}">${escapeHtml(getEmployeeName(w, e.id))}</option>`).join("")}`); }
function getFilteredDepartments() { const q = $("#departmentSearch").val().toLowerCase(), w = loadWorkspace(); return w.departments.filter(d => [d.name, d.description, getEmployeeName(w, d.managerId)].join(" ").toLowerCase().includes(q)); }
function renderDepartments() { const w = loadWorkspace(), rows = getFilteredDepartments(); $("#departmentGrid").html(rows.length ? rows.map(d => `<article class="department-card"><div class="department-card-header"><div><h3 class="department-name">${escapeHtml(d.name)}</h3><span class="manager-pill">Manager: ${escapeHtml(getEmployeeName(w, d.managerId))}</span></div></div><p class="department-desc">${escapeHtml(d.description)}</p><div class="department-stats"><div class="department-stat"><span>Employees</span><strong>${calculateEmployeeCountByDepartment(w, d.id)}</strong></div><div class="department-stat"><span>Payroll</span><strong>${formatCurrency(calculateDepartmentPayroll(w, d.id))}</strong></div></div><div class="department-actions"><button class="btn btn-sm btn-outline-info" onclick="editDepartment('${d.id}')">Edit</button><button class="btn btn-sm btn-outline-danger" onclick="deleteDepartment('${d.id}')">Delete</button></div></article>`).join("") : renderEmptyState("No departments match the search.")); }
function createDepartment(event) { event.preventDefault(); const w = loadWorkspace(), id = $("#departmentId").val(), now = new Date().toISOString(); const p = { id: id || generateId("dept"), name: $("#departmentName").val().trim(), managerId: $("#managerId").val(), description: $("#departmentDescription").val().trim(), createdAt: now, updatedAt: now }; if (id) { w.departments = w.departments.map(d => d.id === id ? { ...d, ...p, createdAt: d.createdAt } : d); addActivityLog("Departments", "Updated department", `Updated department ${p.name}`); } else { w.departments.unshift(p); addActivityLog("Departments", "Created department", `Created department ${p.name}`); } saveWorkspace(w); showStatus("Department saved."); resetDepartmentForm(); renderDepartments(); }
function editDepartment(id) { const d = loadWorkspace().departments.find(item => item.id === id); if (!d) return; $("#departmentFormTitle").text("Edit Department"); $("#departmentId").val(d.id); $("#departmentName").val(d.name); $("#managerId").val(d.managerId); $("#departmentDescription").val(d.description); scrollTo({ top: 0, behavior: "smooth" }); }
function deleteDepartment(id) { const w = loadWorkspace(), d = w.departments.find(item => item.id === id), count = calculateEmployeeCountByDepartment(w, id); if (!d) return; if (count > 0) return showStatus("Cannot delete a department with assigned employees. Reassign employees first.", "danger"); if (!confirm(`Delete ${d.name}?`)) return; w.departments = w.departments.filter(item => item.id !== id); saveWorkspace(w); addActivityLog("Departments", "Deleted department", `Deleted department ${d.name}`); showStatus("Department deleted.", "warning"); renderDepartments(); }
function filterDepartments() { renderDepartments(); }
function resetDepartmentForm() { $("#departmentFormTitle").text("Add Department"); $("#departmentForm")[0].reset(); $("#departmentId").val(""); }
$(document).ready(function () { initShell("departments"); loadDepartmentManagerOptions(); renderDepartments(); $("#departmentForm").on("submit", createDepartment); $("#resetDepartmentForm").on("click", resetDepartmentForm); $("#departmentSearch").on("input", filterDepartments); $("#clearDepartmentFilters").on("click", function () { $("#departmentSearch").val(""); renderDepartments(); }); });
