function loadPayrollFilters(){const w=loadWorkspace();$("#payrollDepartmentFilter").html(`<option value="">All departments</option>${w.departments.map(d=>`<option value="${d.id}">${escapeHtml(d.name)}</option>`).join("")}`);}
function getPayrollEmployees(){const dept=$("#payrollDepartmentFilter").val();return loadWorkspace().employees.filter(e=>!dept||e.departmentId===dept);}
function renderPayrollStats(){const w=loadWorkspace(),emps=getPayrollEmployees(),previews=emps.map(e=>calculatePayrollPreview(w,e.id)),gross=previews.reduce((t,p)=>t+p.salary,0),net=previews.reduce((t,p)=>t+p.netPay,0),ded=previews.reduce((t,p)=>t+p.attendanceDeduction+p.deduction,0),bonus=previews.reduce((t,p)=>t+p.bonus,0);$("#payrollStats").html([["Employees",emps.length,"Included"],["Gross",formatCurrency(gross),"Base salary"],["Bonuses",formatCurrency(bonus),"Manual bonuses"],["Net Pay",formatCurrency(net),`Deductions ${formatCurrency(ded)}`]].map(([l,v,m])=>`<article class="summary-card"><p class="summary-label">${l}</p><p class="summary-value">${v}</p><p class="summary-meta">${m}</p></article>`).join(""));}
function renderPayrollPreview(){const w=loadWorkspace(),emps=getPayrollEmployees();$("#payrollTableWrap").html(emps.length?`<div class="table-responsive"><table class="table table-hover payroll-table"><thead><tr><th>Employee</th><th>Department</th><th>Salary</th><th>Attendance Deduction</th><th>Bonus</th><th>Deduction</th><th>Notes</th><th>Net Pay</th><th></th></tr></thead><tbody>${emps.map(e=>{const p=calculatePayrollPreview(w,e.id),adj=w.payrollAdjustments.find(a=>a.employeeId===e.id)||{};return `<tr><td><div class="payroll-employee"><strong>${escapeHtml(getEmployeeName(w,e.id))}</strong><span>${escapeHtml(e.jobTitle)}</span></div></td><td>${escapeHtml(getDepartmentName(w,e.departmentId))}</td><td>${formatCurrency(p.salary)}</td><td class="deduction-text">${formatCurrency(p.attendanceDeduction)}</td><td><input class="form-control" id="bonus-${e.id}" type="number" value="${Number(adj.bonus||0)}"></td><td><input class="form-control" id="deduction-${e.id}" type="number" value="${Number(adj.deduction||0)}"></td><td><input class="form-control payroll-note" id="notes-${e.id}" value="${escapeHtml(adj.notes||"")}"></td><td class="net-pay">${formatCurrency(p.netPay)}</td><td><button class="btn btn-sm btn-outline-info" onclick="savePayrollAdjustment('${e.id}')">Save</button></td></tr>`;}).join("")}</tbody></table></div>`:renderEmptyState("No employees match this department."));}
function savePayrollAdjustment(employeeId){const w=loadWorkspace(),existing=w.payrollAdjustments.find(a=>a.employeeId===employeeId),payload={id:existing?.id||generateId("payroll"),employeeId,bonus:Number($(`#bonus-${employeeId}`).val())||0,deduction:Number($(`#deduction-${employeeId}`).val())||0,notes:$(`#notes-${employeeId}`).val().trim(),updatedAt:new Date().toISOString()};if(existing)w.payrollAdjustments=w.payrollAdjustments.map(a=>a.employeeId===employeeId?payload:a);else w.payrollAdjustments.push(payload);saveWorkspace(w);addActivityLog("Payroll","Adjusted payroll",`Adjusted payroll for ${getEmployeeName(w,employeeId)}`);showStatus("Payroll adjustment saved.");renderPayrollStats();renderPayrollPreview();}
function calculateNetPay(employeeId){return calculatePayrollPreview(loadWorkspace(),employeeId).netPay;}
function filterPayrollByDepartment(){renderPayrollStats();renderPayrollPreview();}
function exportPayrollPreview(){const w=loadWorkspace(),rows=getPayrollEmployees().map(e=>({employee:getEmployeeName(w,e.id),department:getDepartmentName(w,e.departmentId),...calculatePayrollPreview(w,e.id)}));downloadJson("payroll-preview.json",rows);showStatus("Payroll preview exported.");}
$(document).ready(function(){initShell("payroll");loadPayrollFilters();renderPayrollStats();renderPayrollPreview();$("#payrollDepartmentFilter").on("change",filterPayrollByDepartment);$("#exportPayroll").on("click",exportPayrollPreview);});
