function renderSettingsForm() { const w = loadWorkspace(); $("#companyName").val(w.settings.companyName); $("#adminEmail").val(w.settings.adminEmail); $("#currency").val(w.settings.currency); $("#workingDaysPerMonth").val(w.settings.workingDaysPerMonth); $("#darkMode").prop("checked", w.settings.darkMode); $("#compactSidebar").prop("checked", w.settings.compactSidebar); renderWorkspaceMeta(); }
function renderWorkspaceMeta() { const w = loadWorkspace(), rows = [["Employees", w.employees.length], ["Departments", w.departments.length], ["Attendance", w.attendance.length], ["Leave Requests", w.leaveRequests.length], ["Payroll Adjustments", w.payrollAdjustments.length], ["Activity Logs", w.activityLog.length]]; $("#workspaceMeta").html(rows.map(([l, v]) => `<div class="meta-row"><span>${l}</span><strong>${v}</strong></div>`).join("")); }
function saveSettings(event) { event.preventDefault(); const w = loadWorkspace(); w.settings = { ...w.settings, companyName: $("#companyName").val().trim(), adminEmail: $("#adminEmail").val().trim(), currency: $("#currency").val(), workingDaysPerMonth: Number($("#workingDaysPerMonth").val()) || 26, darkMode: $("#darkMode").is(":checked"), compactSidebar: $("#compactSidebar").is(":checked") }; saveWorkspace(w); addActivityLog("Settings", "Updated settings", "Updated company workspace settings"); showStatus("Settings saved."); renderWorkspaceMeta(); }
function toggleDarkMode() { const w = loadWorkspace(); w.settings.darkMode = $("#darkMode").is(":checked"); saveWorkspace(w); }
function toggleCompactSidebar() { const w = loadWorkspace(); w.settings.compactSidebar = $("#compactSidebar").is(":checked"); saveWorkspace(w); }
function exportWorkspace() { downloadJson("hr-management-workspace.json", loadWorkspace()); showStatus("Workspace exported."); }
function importWorkspace(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = function () { try { const data = JSON.parse(reader.result); saveWorkspace({ ...cloneDefault(), ...data, settings: { ...defaultWorkspace.settings, ...(data.settings || {}) } }); addActivityLog("Settings", "Imported workspace", "Imported workspace JSON"); showStatus("Workspace imported."); renderSettingsForm(); } catch (error) { showStatus("Invalid workspace JSON.", "danger"); } }; reader.readAsText(file); }
function resetDemoWorkspace() { if (!confirm("Reset demo workspace?")) return; resetWorkspace(); showStatus("Demo workspace restored.", "warning"); renderSettingsForm(); }
function clearWorkspace() { if (!confirm("Clear all localStorage workspace data?")) return; localStorage.removeItem(HR_STORAGE_KEY); showStatus("Workspace cleared. Demo data will seed on next load.", "warning"); setTimeout(() => location.reload(), 700); }
$(document).ready(function () { initShell("settings"); renderSettingsForm(); $("#settingsForm").on("submit", saveSettings); $("#darkMode").on("change", toggleDarkMode); $("#compactSidebar").on("change", toggleCompactSidebar); $("#exportWorkspace").on("click", exportWorkspace); $("#importWorkspace").on("change", importWorkspace); $("#importWorkspaceButton").on("click", () => $("#importWorkspace").trigger("click")); $("#resetDemoWorkspace").on("click", resetDemoWorkspace); $("#clearWorkspace").on("click", clearWorkspace); });
