const HR_STORAGE_KEY = "hrManagementPortalWorkspace";
const defaultWorkspace = { settings: { companyName: "NightCity HR", adminEmail: "hr@example.com", currency: "PKR", workingDaysPerMonth: 26, darkMode: true, compactSidebar: false }, employees: [], departments: [], attendance: [], leaveRequests: [], payrollAdjustments: [], activityLog: [] };
function escapeHtml(str){return String(str??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function generateId(prefix){return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;}
function formatDate(dateString){if(!dateString)return"Not set";return new Date(`${dateString}T00:00:00`).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"});}
function getTodayDate(){return new Date().toISOString().slice(0,10);}
function formatCurrency(value){const w=loadWorkspace();return new Intl.NumberFormat("en-PK",{style:"currency",currency:w.settings.currency||"PKR",maximumFractionDigits:0}).format(Number(value)||0);}
function cloneDefault(){return JSON.parse(JSON.stringify(defaultWorkspace));}
function loadWorkspace(){const raw=localStorage.getItem(HR_STORAGE_KEY);if(!raw)return seedDemoData();try{const parsed=JSON.parse(raw);return {...cloneDefault(),...parsed,settings:{...defaultWorkspace.settings,...(parsed.settings||{})},employees:parsed.employees||[],departments:parsed.departments||[],attendance:parsed.attendance||[],leaveRequests:parsed.leaveRequests||[],payrollAdjustments:parsed.payrollAdjustments||[],activityLog:parsed.activityLog||[]};}catch(error){console.error("Workspace data was invalid.",error);return seedDemoData();}}
function saveWorkspace(workspace){localStorage.setItem(HR_STORAGE_KEY,JSON.stringify(workspace));applyThemeSettings();}
function resetWorkspace(){localStorage.removeItem(HR_STORAGE_KEY);return seedDemoData();}
function seedDemoData(){const now=new Date().toISOString();const today=getTodayDate();const departments=[["dept-engineering","Engineering","emp-ali-raza","Software development, QA, integrations, and platform delivery."],["dept-sales","Sales","emp-sana-akhtar","Pipeline management, enterprise accounts, and revenue operations."],["dept-hr","HR","emp-ayesha-khan","Recruiting, employee success, compliance, and workplace policy."],["dept-finance","Finance","emp-bilal-ahmed","Payroll, budgeting, reporting, procurement, and financial controls."],["dept-operations","Operations","emp-usman-tariq","Facilities, vendor coordination, internal systems, and logistics."]].map(([id,name,managerId,description])=>({id,name,managerId,description,createdAt:now,updatedAt:now}));
const employees=[
["emp-ali-raza","Ali","Raza","ali@example.com","+92-300-1234567","dept-engineering","Frontend Developer","Full-time",85000,"Active","2023-02-14"],
["emp-sana-akhtar","Sana","Akhtar","sana@example.com","+92-301-8877441","dept-sales","Sales Manager","Full-time",145000,"Active","2021-09-06"],
["emp-abdul-moiz","Abdul","Moiz","moiz@example.com","+92-302-5550127","dept-engineering","Backend Engineer","Full-time",120000,"Active","2022-04-18"],
["emp-ayesha-khan","Ayesha","Khan","ayesha@example.com","+92-303-2201900","dept-hr","HR Business Partner","Full-time",110000,"On Leave","2020-12-01"],
["emp-bilal-ahmed","Bilal","Ahmed","bilal@example.com","+92-304-7004400","dept-finance","Finance Lead","Full-time",180000,"Active","2019-07-22"],
["emp-hamza-siddiqui","Hamza","Siddiqui","hamza@example.com","+92-305-9191919","dept-sales","Account Executive","Contract",75000,"Active","2024-01-10"],
["emp-fatima-noor","Fatima","Noor","fatima@example.com","+92-306-3334545","dept-hr","Recruitment Intern","Intern",45000,"Active","2025-03-03"],
["emp-usman-tariq","Usman","Tariq","usman@example.com","+92-307-8080770","dept-operations","Operations Manager","Part-time",95000,"Resigned","2021-05-15"]
].map(([id,firstName,lastName,email,phone,departmentId,jobTitle,employmentType,monthlySalary,status,joiningDate])=>({id,firstName,lastName,email,phone,departmentId,jobTitle,employmentType,monthlySalary,status,joiningDate,createdAt:now,updatedAt:now}));
const attendance=[
["att-001","emp-ali-raza",today,"Present","09:05","18:00","Sprint planning"],["att-002","emp-sana-akhtar",today,"Present","09:00","18:10","Client demos"],["att-003","emp-abdul-moiz",today,"Remote","09:20","18:15","API support"],["att-004","emp-ayesha-khan",today,"Absent","","","Leave in progress"],["att-005","emp-bilal-ahmed",today,"Late","10:05","18:30","Bank meeting"],["att-006","emp-hamza-siddiqui",today,"Present","08:55","17:50","Pipeline updates"],["att-007","emp-fatima-noor",today,"Present","09:15","17:30","Interview scheduling"],["att-008","emp-ali-raza","2026-07-04","Remote","09:12","18:02","Feature QA"],["att-009","emp-sana-akhtar","2026-07-04","Present","09:01","18:04","Sales review"],["att-010","emp-abdul-moiz","2026-07-04","Late","10:20","18:20","Traffic delay"],["att-011","emp-bilal-ahmed","2026-07-04","Present","08:50","17:55","Payroll audit"],["att-012","emp-hamza-siddiqui","2026-07-04","Absent","","","Unplanned absence"],["att-013","emp-fatima-noor","2026-07-04","Present","09:25","17:40","Candidate calls"],["att-014","emp-usman-tariq","2026-07-04","Remote","09:30","16:45","Handover docs"]
].map(([id,employeeId,date,status,checkIn,checkOut,notes])=>({id,employeeId,date,status,checkIn,checkOut,notes,createdAt:now}));
const leaveRequests=[
["leave-001","emp-ayesha-khan","Annual","2026-07-05","2026-07-08",4,"Family travel","Approved"],["leave-002","emp-ali-raza","Sick","2026-07-10","2026-07-12",3,"Medical rest","Pending"],["leave-003","emp-hamza-siddiqui","Casual","2026-07-15","2026-07-15",1,"Personal work","Pending"],["leave-004","emp-fatima-noor","Unpaid","2026-07-20","2026-07-21",2,"University paperwork","Rejected"],["leave-005","emp-bilal-ahmed","Casual","2026-07-24","2026-07-24",1,"Bank appointment","Approved"],["leave-006","emp-abdul-moiz","Annual","2026-08-01","2026-08-05",5,"Vacation","Pending"]
].map(([id,employeeId,leaveType,startDate,endDate,days,reason,status])=>({id,employeeId,leaveType,startDate,endDate,days,reason,status,createdAt:now,updatedAt:now}));
const payrollAdjustments=[["payroll-001","emp-ali-raza",7000,0,"Feature delivery bonus"],["payroll-002","emp-sana-akhtar",15000,0,"Quarterly sales incentive"],["payroll-003","emp-abdul-moiz",5000,2500,"Late deduction preview"],["payroll-004","emp-bilal-ahmed",10000,0,"Audit close support"],["payroll-005","emp-hamza-siddiqui",3000,5000,"Absence adjustment"]].map(([id,employeeId,bonus,deduction,notes])=>({id,employeeId,bonus,deduction,notes,updatedAt:now}));
const activityLog=[["log-001","Employees","Created employee","Created employee Ali Raza"],["log-002","Departments","Updated department","Assigned Sana Akhtar as Sales manager"],["log-003","Attendance","Marked attendance","Marked Abdul Moiz as Remote"],["log-004","Leave","Approved leave","Approved annual leave for Ayesha Khan"],["log-005","Payroll","Adjusted payroll","Added sales incentive for Sana Akhtar"],["log-006","Settings","Seeded workspace","Demo HR workspace initialized"]].map(([id,module,action,detail])=>({id,module,action,detail,createdAt:now}));
const workspace={...cloneDefault(),departments,employees,attendance,leaveRequests,payrollAdjustments,activityLog};saveWorkspace(workspace);return workspace;}
function addActivityLog(module,action,detail){const w=loadWorkspace();w.activityLog.unshift({id:generateId("log"),module,action,detail,createdAt:new Date().toISOString()});w.activityLog=w.activityLog.slice(0,60);saveWorkspace(w);}
function getEmployeeName(w,employeeId){const e=w.employees.find(item=>item.id===employeeId);return e?`${e.firstName} ${e.lastName}`:"Unassigned";}
function getDepartmentName(w,departmentId){const d=w.departments.find(item=>item.id===departmentId);return d?d.name:"Unassigned";}
function calculateEmployeeCountByDepartment(w,departmentId){return w.employees.filter(e=>e.departmentId===departmentId).length;}
function calculateDepartmentPayroll(w,departmentId){return w.employees.filter(e=>e.departmentId===departmentId).reduce((t,e)=>t+Number(e.monthlySalary||0),0);}
function calculateAttendanceStats(w,date){const r=w.attendance.filter(i=>i.date===date);return{total:r.length,present:r.filter(i=>i.status==="Present").length,absent:r.filter(i=>i.status==="Absent").length,late:r.filter(i=>i.status==="Late").length,remote:r.filter(i=>i.status==="Remote").length};}
function calculateLeaveDays(startDate,endDate){if(!startDate||!endDate)return 0;const s=new Date(`${startDate}T00:00:00`),e=new Date(`${endDate}T00:00:00`);if(Number.isNaN(s.getTime())||Number.isNaN(e.getTime())||e<s)return 0;return Math.round((e-s)/86400000)+1;}
function calculatePayrollPreview(w,employeeId){const e=w.employees.find(item=>item.id===employeeId);if(!e)return{salary:0,attendanceDeduction:0,bonus:0,deduction:0,netPay:0};const a=w.payrollAdjustments.find(item=>item.employeeId===employeeId)||{};const daily=Number(e.monthlySalary||0)/(Number(w.settings.workingDaysPerMonth)||26);const month=getTodayDate().slice(0,7);const records=w.attendance.filter(item=>item.employeeId===employeeId&&item.date.startsWith(month));const attendanceDeduction=Math.round(records.filter(i=>i.status==="Absent").length*daily+records.filter(i=>i.status==="Late").length*daily*.25);const bonus=Number(a.bonus||0),deduction=Number(a.deduction||0),salary=Number(e.monthlySalary||0);return{salary,attendanceDeduction,bonus,deduction,netPay:Math.max(0,Math.round(salary-attendanceDeduction+bonus-deduction))};}
function renderSidebar(activePage){const items=[["dashboard","Dashboard","DB","index.html"],["employees","Employees","EM","employees.html"],["attendance","Attendance","AT","attendance.html"],["leave","Leave Requests","LV","leave-requests.html"],["departments","Departments","DP","departments.html"],["payroll","Payroll Preview","PY","payroll.html"],["settings","Settings","ST","settings.html"]];return `<aside class="sidebar" id="sidebar"><div class="sidebar-brand"><div class="brand-mark">HR</div><div class="brand-copy"><p class="brand-title">HR Management Portal</p><p class="brand-subtitle">Enterprise workspace</p></div></div><nav class="sidebar-nav" aria-label="Primary navigation">${items.map(([page,label,icon,href])=>`<a class="sidebar-link ${page===activePage?"active":""}" href="${href}" data-page="${page}"><span class="nav-icon">${icon}</span><span class="nav-label">${label}</span></a>`).join("")}</nav><div class="sidebar-footer"><strong>Local workspace</strong><p class="mb-0 mt-1">Demo data, settings, and HR activity are saved in this browser.</p></div></aside>`;}
function setActiveNav(){const current=window.location.pathname.split("/").pop()||"index.html";$(".sidebar-link").each(function(){$(this).toggleClass("active",$(this).attr("href")===current);});}
function showStatus(message,type="success"){const box=$("#statusMessage");if(!box.length)return;box.removeClass("success warning danger show").addClass(`${type} show`).text(message);window.clearTimeout(window.hrStatusTimer);window.hrStatusTimer=window.setTimeout(()=>box.removeClass("show"),3200);}
function renderEmptyState(message){return `<div class="empty-state"><div><strong>No records found</strong><span>${escapeHtml(message)}</span></div></div>`;}
function downloadJson(filename,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
function copyText(text,message="Copied to clipboard."){if(!navigator.clipboard){showStatus("Clipboard API is not available in this browser.","warning");return;}navigator.clipboard.writeText(text).then(()=>showStatus(message,"success")).catch(()=>showStatus("Unable to copy text.","danger"));}
function applyThemeSettings(){const raw=localStorage.getItem(HR_STORAGE_KEY);if(!raw)return;try{const w=JSON.parse(raw);document.body.classList.toggle("light-mode",!w.settings?.darkMode);document.body.classList.toggle("compact-sidebar",Boolean(w.settings?.compactSidebar));}catch(error){console.error("Unable to apply theme settings.",error);}}
function slugify(text){return String(text||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}
function initShell(active){$("#sidebarMount").html(renderSidebar(active));setActiveNav();applyThemeSettings();}
$(document).ready(function(){loadWorkspace();applyThemeSettings();$(document).on("click","#mobileNavToggle",()=>$("body").toggleClass("sidebar-open"));$(document).on("click",".sidebar-link",()=>$("body").removeClass("sidebar-open"));});
